### ISSUE TITLE
Ingress filters out annotations

### ISSUE THREAD

**Issue by alexkrebiehlKR** [Neotys-Labs/helm-neoload-web#22]
The annotation filtering on the ingress resource (https://github.com/Neotys-Labs/helm-neoload-web/blob/master/templates/ingress.yaml#L19) prevents adding additional annotations such as `cert-manager.io/issuer`. Please add an option to specify annotations besides those that begin with the ingress class name.

**Comment by FROD-Neotys** [comment]
Hello and thank you for the suggestion. We have decided to remove that filtering so that you have full control over the annotations you want to add.
