### ISSUE TITLE
helm release 2.7.0 and kubernetes image 4.0.0 not available

### ISSUE THREAD

**Issue by nitharsandvag** [Neotys-Labs/helm-neoload-web#27]
Hello,

according to the documentation now it is supported in Kubernetes 1.22.0.
But latest changes are not released as new helm version, it is still 2.6.1 and also there is no 4.0.0 image for backend and frontend:
https://hub.docker.com/r/neotys/neoload-web-frontend/tags
https://hub.docker.com/r/neotys/neoload-web-backend/tags

Thanks,
Nitharsan

**Comment by lcharlois-neotys** [comment]
Hello Nitharsan,

NeoLoad Web 4.0 should be released next week.
The chart will be released at the same time.

Thanks,
Laurent.
